# Generated by Django 5.2 on 2025-05-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_profile_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='selected_avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='selected_avatar_color',
        ),
    ]
