# Generated by Django 5.2 on 2025-05-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_title'),
        ('blog', '0015_manual_add_image'),
    ]

    operations = [
    ]
